name: RutGonLenhPlugin
version: 1.0
main: com.yourname.rglplugin.RutGonLenhPlugin
api-version: 1.20 # Đặt phiên bản API phù hợp
commands:
  rgl:
    description: Plugin quan ly lenh rut gon.
    usage: /rgl reload
    permission: rglplugin.admin # Đây là quyền cho lệnh /rgl
permissions:
  rglplugin.admin:
    description: Cho phep reload plugin.
    default: op # Mặc định chỉ có OP mới có quyền này